### ISSUE TITLE
Transfer this repository to the pytransitions organization

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions-anyio#1]
@aleneum I've sent you an invite.
Please move this repository to the pytransitions organization.

**Comment by aleneum** [comment]
Hi @thedrow,

sounds like a plan. Unfortunately I was too slow and the invitation expired. Could you send it again?

**Comment by thedrow** [comment]
Done.

**Comment by aleneum** [comment]
as far as i can tell i cannot move it (lack of permissions probably). but I invited you to `pytransitions`. As a member you should have the rights to create new repositories and thus also move the repo.
