### ISSUE TITLE
Release first version to PyPi

### ISSUE THREAD

**Issue by thedrow** [pytransitions/transitions-anyio#4]
Hi @aleneum,

We should make this library available on PyPi.
Would you mind registering it and giving me release access?

**Comment by aleneum** [comment]
Hello @thedrow and happy new year 🎆!

>  Would you mind registering it and giving me release access?

Sure, please have a look at #5. I am fairly new to working with poetry. If these changes are okay, I will publish the package.

**Comment by thedrow** [comment]
Merged.

**Comment by aleneum** [comment]
whats your pypi username?

**Comment by aleneum** [comment]
Ah, found you! ([ref](https://pypi.org/user/the_drow/)). Could you register an account on test.pypi.org as well?

**Comment by aleneum** [comment]
You should have received an invite from pypi.org

**Comment by thedrow** [comment]
> Ah, found you! ([ref](https://pypi.org/user/the_drow/)). Could you register an account on test.pypi.org as well? 

I'll add it to my to do list.

**Comment by thedrow** [comment]
For some reason, it didn't take when I joined.
Can you please invite me again?

**Comment by aleneum** [comment]
Invite did expire. You should have received a new one.

**Comment by thedrow** [comment]
Thanks!
